const ContactActionTypes = {
  CREATECONTACT_SUCCESS: "CREATECONTACT_SUCCESS",
  CREATECONTACT_FAIL: "CREATECONTACT_FAIL",
  CONTACTSLOAD_SUCCESS: "CONTACTSLOAD_SUCCESS",
  CONTACTSLOAD_FAIL: "CONTACTSLOAD_FAIL",
  REMOVECONTACT_SUCCESS: "REMOVECONTACT_SUCCESS",
  REMOVECONTACT_FAIL: "REMOVECONTACT_FAIL",
  GROUPSLOAD_SUCCESS: "GROUPSLOAD_SUCCESS",
  GROUPSLOAD_FAIL: "GROUPSLOAD_FAIL",
  REMOVEGROUP_SUCCESS: "REMOVEGROUP_SUCCESS",
  CREATEGROUP_SUCCESS: "CREATEGROUP_SUCCESS",
  SEARCH_SUCCESS: "SEARCH_SUCCESS",
  EDITCONTACT_SUCCESS: "EDITCONTACT_SUCCESS",
  UPDATECONTACT_SUCCESS: "UPDATECONTACT_SUCCESS",
  EDITGROUP_SUCCESS: "EDITGROUP_SUCCESS",
  UPDATEGROUP_SUCCESS: "UPDATEGROUP_SUCCESS",
};

export default ContactActionTypes;
